CREATE PROC [dbo].[sp_Kiem_Tra_MasoDDH]
@MasoDDH nchar(8)
AS
BEGIN
	IF EXISTS(SELECT 1 FROM DatHang DDH WHERE DDH.MasoDDH = @MasoDDH)
		RETURN 1;
	ELSE
	IF EXISTS(SELECT 1 FROM LINK0.QLVT.dbo.DatHang DDH WHERE DDH.MasoDDH = @MasoDDH)
		RETURN 1;
	RETURN 0;
END